### ISSUE TITLE
Doesn't work on build 

### ISSUE THREAD

**Issue by mbpmm** [naelstrof/SkinnedMeshDecals#1]
Hi, i came across your repository searching for skinned mesh decals for my university project. I found a problem, when you build the project decals doesn't appear, i think it must be a shader issue i tried everything but it didn't work, and im not good with shader language. Hope you can give me a hand.
Thank for your time, sorry for my english. Greetings from Argentina.

**Comment by naelstrof** [comment]
Oh my gosh I'm so sorry, yeah I actually fixed this problem. It was because I was trying to render using mipmaps!

Mipmaps are treated differently in the editor for whatever reason. Try the commit I just posted 740a509f0dbae7798795bdd00d8c1239a86b3dca

I changed the interface slightly (hit normal is reversed as we're pointing a camera, and you have to offset it a bit depending on the depth).

I also added the ability to paint onto lightmapped static geometry! Let me know if you have any other issues.

**Comment by naelstrof** [comment]
I also made a full changelog on the release here: https://github.com/naelstrof/SkinnedMeshDecals/releases/tag/v4

**Comment by mbpmm** [comment]
It worked great, i had to make some adjustments in the PaintDecal script with the near and far plane from the camera to make it  work on our game, other than that everything worked perfect. 

Thank you!

**Comment by frankvega2010** [comment]
Thank you for the quick response! We were having some troubles with it and we didn't know if we did something wrong or if it had something to do with the decals.

**Comment by naelstrof** [comment]
> Thank you for the quick response! We were having some troubles with it and we didn't know if we did something wrong or if it had something to do with the decals.

Yeah! Feel free to bug me about any other problems you have, I use this tech too so I love to hear of potential problems I might run into.
