### ISSUE TITLE
HDRP Shader Errors with Unity 2020.3.0f1 [HDRP 10.3.2]

### ISSUE THREAD

**Issue by Snow-Okami** [naelstrof/SkinnedMeshDecals#2]
I am getting a few shader errors on 2020.3.0f1 with HDRP 10.3.2.

> Shader error in 'Decalable/HDRP/Lit': 'GetDecalSurfaceData': no matching 2 parameter function at line 541 (on d3d11)

> Shader error in 'Decalable/HDRP/Lit': 'LightLoop': cannot convert output parameter from 'struct LightLoopOutput' to 'float3' at line 4251 (on d3d11)

> Shader error in 'Decalable/HDRP/StaticLit': 'GetDecalSurfaceData': no matching 2 parameter function at line 541 (on d3d11)

> Shader error in 'Decalable/HDRP/StaticLit': 'LightLoop': cannot convert output parameter from 'struct LightLoopOutput' to 'float3' at line 4251 (on d3d11)

I don't have any experience with Amplify Shader Editor or a majority of shader code so I am not quite sure how to fix it.

**Comment by naelstrof** [comment]
Sorry they were made for HDRP 7.3.1. Simply recompiling them with amplify should work! You might have to switch the template back and forth in order to reset all the shader parameters.

You should be able to use a ShaderGraph version as well, the most important thing is that the shader has a `_DecalColorMap` texture input.

Otherwise I'll get around to updating it! I'm a bit busy right now but in the next couple days-- definitely.

**Comment by naelstrof** [comment]
As of https://github.com/naelstrof/SkinnedMeshDecals/commit/f783e873ab92f214ca45539a06f69af2b2d39d98, the shaders should work with 10.3.2!

Let me know if you have any other troubles.

**Comment by Snow-Okami** [comment]
Wow! You work fast. It is fixed for me now and working!
